
gitrepo:
  enabled: true
  name: "test"
  url: https://github.com/group/repo
  interval: "5m0s"
  ref:
    tag: "0.0.1"
    # branch: ""
    # commit: ""
    # semver: ""

helmrelease:
  enabled: true
  name: "test"
  sourceType: "git"
  targetNamespace: test
  chartInterval: "5m"
  gitRepo:
    path: "chart/"
    gitRepoName: "test"
    gitRepoNamespace: "test"
  helmRepo:
    chartName: "test"
    tag: "0.1.0"
    repoName: "test"
    helmRepoNamespace: "test"
  timeout: 10m
  interval: 2m
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: true
  valuesFrom: []
  dependsOn: []
  postRenderers: {}
  



