
gitrepo:
  enabled: true
  url: https://github.com/group/repo
  interval: "5m0s"
  ref:
    path: "./chart"
    tag: "0.0.1"
    # branch: ""
    # commit: ""
    # semver: ""

helmrelease:
  enabled: true
  sourceType: "git"
  targetNamespace: test
  gitRepo:
    path: "chart/"
    gitRepoName: "test"
    gitRepoNamespace: "test"
  helmRepo:
    chartName: "test"
    tag: "0.1.0"
    repoName: "test"
    helmRepoNamespace: "test"
  valuesFrom: []
  dependsOn: []
  postRenderers: {}
  



