
gitrepo:
  enabled: true
  url: https://github.com/group/repo
  ref:
    branch: "main"

helmrelease:
  enabled: true
  sourceType: "git"
  targetNamespace: test
  gitRepo:
    path: "chart/"
    gitRepoName: "test"
    gitRepoNamespace: "test"
  helmRepo:
    chartName: "test"
    tag: "0.1.0"
    repoName: "test"
    helmRepoNamespace: "test"
  postRenderers: {}
  



