{{- if .Values.gitrepo.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ .Values.gitrepo.name  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  interval: {{ .Values.gitrepo.interval }}
  url: {{ .Values.gitrepo.url }}
  ref:
    {{- include "validRef" .Values.gitrepo.ref | nindent 4 }}
  {{ include "gitIgnore" . }}
{{- end }}