{{- if .Values.helmrelease.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .Values.helmrelease.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  targetNamespace: {{ .Values.helmrelease.targetNamespace }}
  chart:
    spec:
      {{- if eq .Values.helmrelease.sourceType "git" }}
      chart: {{ .Values.helmrelease.gitRepo.path }}
      sourceRef:
        kind: GitRepository
        name: {{ .Values.helmrelease.gitRepo.gitRepoName }}
        namespace: {{ .Values.helmrelease.gitRepo.gitRepoNamespace }}
      {{- else }}
      chart: {{ .Values.helmrelease.helmRepo.chartName }}
      version: {{ .Values.helmrelease.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.helmrelease.helmRepo.repoName }}
        namespace: {{ .Values.helmrelease.helmRepo.helmRepoNamespace}}
      {{- end }}
      interval: 5m

  {{- if .Values.helmrelease.postRenderers }}
  postRenderers:
  {{ toYaml .Values.helmrelease.postRenderers | nindent 4 }}
  {{- end }}
  {{- if .Values.helmrelease.valuesFrom }}
  valuesFrom:
    {{- toYaml .Values.helmrelease.valuesFrom | nindent 4 }}
  {{- end }}
  {{- if .Values.helmrelease.dependsOn }}
  dependsOn:
    {{- toYaml .Values.helmrelease.dependsOn | nindent 4 }}
  {{- end }}
{{- end }}